services:
  local-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  local-redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data_container: